---
io-services:
  reader:
    class: FileReaderService
    name: FileReaderService
  writer:
    class: FileWriterService
    name: FileWriterService

services:
  - class: segmentor_actor
    name: segmentor_actor
    lang: cpp

mime-types:
  - binary/bytes