---
io-services:
  reader:
    class: FileReaderService
    name: FileReaderService
  writer:
    class: DummyWriterService
    name: DummyWriterService

services:
  - class: segmentor_actor
    name: segmentor_actor
    lang: cpp

configuration:
  io-services:
    reader:
      eventSize: 80000 
      events: 1000
  services:
    segmentor_actor:
      INI_FILE: config/localhost/segmentor.ini

mime-types:
  - binary/bytes