---
io-services:
  reader:
    class: ByteBufferInputService
    name: ByteBufferInputService
  writer:
    class: DummyWriterService
    name: DummyWriterService

services:
  - class: segmentor_actor
    name: segmentor_actor
    lang: cpp

configuration:
  io-services:
    ByteBufferInputService:
      eventSize: 1024 
      events: 1000
  services:
    segmentor_actor:
      INI_FILE: config/live/segmentor.ini

mime-types:
  - binary/bytes