---
io-services:
  reader:
    class: FileReaderService
    name: FileReaderService
  writer:
    class: DummyWriterService
    name: DummyWriterService

services:
  - class: segmentor_actor
    name: segmentor_actor
    lang: cpp

configuration:
  services:
    segmentor_actor:
      INI_FILE: config/live/segmentor.uri

mime-types:
  - binary/bytes