---
io-services:
  reader:
    class: FileReaderService
    name: FileReaderService
  writer:
    class: DummyWriterService
    name: DummyWriterService

services:
  - class: segmentor_actor
    name: segmentor_actor
    lang: cpp

configuration:
  services:
    segmentor_actor:
      EJFAT_URI: this is a test to see how I parse stuff

mime-types:
  - binary/bytes