---
io-services:
  reader:
    class: BufferSizeReaderService
    name: BufferSizeReaderService
  writer:
    class: FileWriterService
    name: FileWriterService

services:
  - class: reassembler_actor
    name: reassembler_actor
    lang: cpp

configuration:
  io-services:
    reader:
      events: 2
  services:
    reassembler_actor:
      INI_FILE: config/localhost/reassembler.ini

mime-types:
  - binary/bytes
  - sint32