---
io-services:
  reader:
    class: org.jlab.ersap.e2sar.ByteBufferInputService
    name: ByteBufferInputService
  writer:
    class: org.jlab.ersap.e2sar.DummyWriterService
    name: DummyWriterService

services:
  - class: segmentor_actor
    name: segmentor_actor
    lang: cpp

configuration:
  io-services:
    reader:
      eventSize: 80000 
      events: 1000
  services:
    segmentor_actor:
      INI_FILE: config/live/segmentor.ini

mime-types:
  - binary/bytes